routes/web.php
<?php

use App\Http\Controllers\AdminCertificateController;
use App\Http\Controllers\MainController;
use App\Http\Controllers\AdminProgramController;
use App\Http\Controllers\AdminScheduleController;
use App\Http\Controllers\WeekController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [MainController::class, 'index'])->name('index');
Route::get('/schedule/{schedule}', [WeekController::class, 'index'])->name('schedule.show');
Route::get('/program/{program}', [MainController::class, 'show'])->name('program.show');
Route::post('/feedback', [MainController::class, 'store_feedback'])->name('feedback.store');

Route::prefix('admin')->name('admin.')->group(function (){
    Route::resource('programs', AdminProgramController::class)->names('program');
    Route::resource('certificates', AdminCertificateController::class)->names('certificate');
    Route::resource('schedules', AdminScheduleController::class)->except('show')->names('schedule');
});

app/Models/Program.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Program extends Model
{
    protected $fillable = [
        'id',
        'title',
        'description',
        'short_description',
        'img',
        'updated_at',
        'created_at',
        'user_id',
     ];

        public function user() {
        return $this->belongsTo(User::class);
    }
}

resources/views/admin/program/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h1>Мероприятие</h1>
    <form  class="m-5" method="post" enctype="multipart/form-data" action="{{ route('admin.program.store') }}">
        @csrf
        <div class="form-group">
            <label for="title">Название</label>
            <input type="text" class="form-control" id="title" name="title" placeholder="title">
        </div>
        <div class="form-group">
            <label for="exampleFormControlImadge">image</label>
            <input type="file" class="form-control-file" id="exampleFormControlImadge" name="img">
        </div>
        <div class="form-group">
            <label for="exampleFormControlTextarea">Описание</label>
            <textarea class="form-control" id="exampleFormControlTextarea" rows="10" name="description"></textarea>
        </div>
        <div class="btn-group">
            <input class="btn btn-primary"type="submit" value="Сохранить">
            <input class="btn btn-link"type="reset" value="Сбросить">
        </div>
    </form>
</div>
@endsection

resources/views/admin/program/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <form class="m-5" enctype="multipart/form-data" action="{{ route('admin.program.update', $item->id) }}" method="post">
    @csrf
    @method('PUT')
      <div class="form-group">
            <label for="exampleFormControlInput">Название</label>
            <input type="text" class="form-control" id="exampleFormControlInput" name="title" placeholder="title" value="{{ $item->title }}">
        </div>
        <div class="from-group">
            <img src="{{ asset('/storage/' . $item->img) }}" alt="">
        </div>
        <div class="form-group">
            <label for="exampleFormControlFileImadge">image</label>
            <input type="file" class="form-control-file" id="exampleFormControlFileImadge" name="img" value="{{ $item->img }}">
        </div>
        <div class="form-group">
           <label for="exampleFormControlTextarea">Описание</label>
           <textarea class="form-control" id="exampleFormControlTextarea" rows="10" name="description">{{ $item->description }}</textarea>
      </div>
       <div class="btn-group">
          <input class="btn btn-primary"type="submit" value="Сохранить">
          <input class="btn btn-link"type="reset" value="Сбросить">
      </div>
    </form>
</div>

@endsection

resources/views/admin/program/index.blade.php
@extends('layouts.app')

@section('content')
<section class="client_section layout_padding" id="program">
    <a href="#program"></a>
    <div class="container layout_padding2-top">
        <div class="heading_container">
            <h2>
                Мероприятия
            </h2>
        </div>
    </div>
    <div class="events-page-section spad">
        <div class="container">
            <div class="row">
               @foreach ($listProgram as $item)
                <div class="col-lg-4 col-md-6">
                    <div class="blog-item">
                        <img src="{{ asset('/storage/' . $item->img) }}" alt="">
                        <div class="bi-text">
                            <h2><a href="{{ route('admin.program.show', $item->id) }}">{{ $item->title }}</a></h2>

                        </div>
                        <div class="bi-footer">
                            <div class="bi-cata"><p>{{ $item->short_description }}</p></div>
                            <div class="bi-social">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                               <a href="#"><i class="fa fa-twitter"></i></a>

                            </div>
                        </div>
                    </div>
                </div>
                @endforeach
            </div>
            <div class="site-pagination pt-3">
              {{ $listProgram->links() }}
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/admin/program/store.blade.php
@extends('layouts.app')

@section('content')
    <section class="blog-details-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="blog-details">
                        <div class="blog-preview">
                            <img class="col-md-2" src="{{ asset('/storage/' . $item->img) }}" alt="">
                        </div>
                        <h2>{{ $item->title }}</h2>
                        <div class="blog-meta"><p><i class="material-icons">автор: </i> {{ $item->user->name }} </p></div>

                        @foreach(explode(PHP_EOL, $item->description) as $paragraph)
                        <p>{{{ $paragraph }}}</p>
                        @endforeach

                        <div class="blog-gallery">
                            <div class="row">
                                <div class="col-md-4">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-7">
                                <div class="ed-cata"><p><i class="material-icons">дата публикации: </i> {{ $item->created_at->format('d.m.y') }} </p></div>

                                @if ($item->created_at < $item->updated_at)
                                <div class="ed-cata"><p><i class="material-icons">изменён: </i> {{ $item->updated_at->format('d.m.y') }} </p></div>
                                @endif

                            </div>
                            <div class="col-sm-5 text-left text-sm-right pt-4 pt-sm-0">
                                <div class="ed-social">
                                    <a href="#"><i class="fa fa-facebook"></i></a>
                                    <a href="#"><i class="fa fa-instagram"></i></a>
                                    <a href="#"><i class="fa fa-twitter"></i></a>
                                    <a href="#"><i class="fa fa-linkedin"></i></a>
                                </div>
                            </div>
                        </div>
                        <div class="btn-group">
                                 <a href="{{ route('admin.program.edit', $item->id) }}" class="btn btn-primary">редактировать</a>
                                <form action="{{ route('admin.program.destroy', $item->id) }}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <input class="btn btn-link" type="submit" value="удалить">
                                </form>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection